use libc++ instead of libstdc++ with Clang on Linux
to fix this error:

/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/cstddef:51:11:
error: no member named 'max_align_t' in the global namespace using ::max_align_t;

related:

https://github.com/philsquared/Catch/issues/334