Update cmake.yml, use gcc11 instead of gcc10
original error message:
 gcc@10: The x86_64 architecture is required for this software.
==> Downloading https://ghcr.io/v2/homebrew/core/boost/manifests/1.84.0_1
Error: gcc@10: An unsatisfied requirement failed this build.